version: '3'
services:
  gondolin-server:
    build:
      context: .
    ports:
      - 3000:3000
  gondolin-postgis:
    image: mdillon/postgis:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gondolin
      POSTGRES_PASSWORD: gondolin
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data:Z
